remove-browser-console-clear
jesims/customs pull request #9
Opened 2021-01-26 10:27 UTC by AndreTheHunter

2021-01-26 10:30 UTC, AndreTheHunter commented on src/io/jesi/customs/runner/browser.cljs
> -  (js/console.clear)
Removed
Users can still do
```clj
(defn ^:dev/after-load clear-console []
  (js/console.clear))
```
if they want to clear the console

2021-01-26 22:33 UTC, axrs requested changes
And the checkbox items

2021-01-26 22:33 UTC, axrs commented on customs.iml
> +<module cursive.leiningen.project.LeiningenProjectsManager.displayName="io.jesi/customs:1.2.0" cursive.leiningen.project.LeiningenProjectsManager.isLeinModule="true" type="JAVA_MODULE" version="4">
IMls refresh if version changed?

2021-01-31 10:48 UTC, AndreTheHunter commented on src/io/jesi/customs/spy.cljc
> +                            (conj! `(pr-str ~form))))
Fix potential bug

2021-01-31 10:48 UTC, AndreTheHunter commented on test/io/jesi/customs/spy_test.cljc
> +    #?(:clj (comment                                        ;Fails since Actual is a vector (not a list)
Not sure why it's in a vector...

2021-01-31 10:49 UTC, AndreTheHunter commented on customs.iml
> +<module cursive.leiningen.project.LeiningenProjectsManager.displayName="io.jesi/customs:1.2.0" cursive.leiningen.project.LeiningenProjectsManager.isLeinModule="true" type="JAVA_MODULE" version="4">
Updated `.iml`

2021-01-31 10:49 UTC, AndreTheHunter commented on src/io/jesi/customs/runner/browser.cljs
> -  (js/console.clear)
Added to Changelog

2021-01-31 22:20 UTC, axrs submitted a review, later dismissed

2021-01-31 23:24 UTC, axrs approved these changes

2021-01-31 23:24 UTC, merged